### ISSUE TITLE
AmnestyTech list, maintained by scafroglia93

### ISSUE THREAD

**Issue by beerisgood** [Kees1958/W3C_annual_most_used_survey_blocklist#11]
What did you think about that list?:
https://github.com/scafroglia93/blocklists/blob/master/blocklists-main.txt

@scafroglia93 build this from:
https://github.com/AmnestyTech/investigations/ as better usable list

**Comment by Kees1958** [comment]
It is a large list :-) Do I understand correctly that it " contains indicators of compromise extracted from some of Amnesty International's technical investigations in targeted threats against human rights defenders". Considering its origin and purpose I have nothing against starring it to give them a thumbs up, but I doubt whether it would add any additional trackers of ad networks (considering they probably monitor their brand imago, because bad press is bad for their business).

Lets keep an issue open with a general name to exchange ideas and thoughts. I am closing this one for now

**Comment by beerisgood** [comment]
Alright!
Thanks for your response <3
