### ISSUE TITLE
Netflix.com blocking

### ISSUE THREAD

**Issue by Pauwelz** [Kees1958/W3C_annual_most_used_survey_blocklist#29]
Hi,

Appreciate the work you're doing!
The TOP_EU_US_Ads_Trackers_HOST list recently got added to WaLLy3K's [The Big Blocklist Collection](https://firebog.net/), and after my pihole updatelists script ran I noticed that Netflix got blocked.

I guess this is one of those "Necessary evils" websites that probably should be whitelisted.

**Comment by beerisgood** [comment]
@Kees1958 how should we handle the ABP list for Netflix.com?
https://github.com/Kees1958/W3C_annual_most_used_survey_blocklist/blob/master/TOP_EU_US_Ads_Trackers_ABP#L2830

**Comment by Pauwelz** [comment]
Can confirm it's working again, thanks!

**Comment by Kees1958** [comment]
Guess we can remove Netflix. Netflix (like amazon) has so much traffic that its trackers have high prevalence, while they should be treated as semi-first party. I have never seen Netflix tracking me, because i use the Netflix App. So my proposal is to remove the block for Netflix third-party?

@beerisgood are you okay with removing it? (when no I will put it back in again)

**Comment by beerisgood** [comment]
Fully agree with you. I also use Windows10 & Xbox Netflix App.
