### ISSUE TITLE
Reason why sketchfab.com is included on the list ?

### ISSUE THREAD

**Issue by pierreant-p** [Kees1958/W3C_annual_most_used_survey_blocklist#44]
Hi,

I'm a co-founder and lead of the web team at sketchab.com.

Can you share the reasons behind sketchfab.com being added to this list?
(This was reported to us today by a user who couldn't access the site).

Can this be reconsidered, as we are not an ad company but a plaform where artists can share their 3d models online?

Thanks,

PA

**Comment by Kees1958** [comment]
Pierrant

In 2020 I evaluated a source which was faulty. I decided to reject it and uploaded the list (after having it sorted and cleaned offline). Due to the late hours I used the wrong version with faults (legit websites). Apologize for that. As users may have noted the rule count is dropping. This is due to a manual cleanup (I am half way at the moment).

Thanks for reporting

Regards

Kees

**Comment by pierreant-p** [comment]
Awesome, thanks !
