### ISSUE TITLE
Error in the version?

### ISSUE THREAD

**Issue by SampeiNihira** [Kees1958/W3C_annual_most_used_survey_blocklist#66]
2022.04.021

OT
Someone noticed that you dropped MT.
I lasted a short time too, not a very congenial environment for me.

Best regards.

**Comment by Kees1958** [comment]
Well it was BoraMurdar who could not appreciate feedback on his security setup and banned me :-) for this
https://malwaretips.com/threads/boramurdars-system-2022.112908/#post-980520

**Comment by SampeiNihira** [comment]
OT

Yep BoraMurdar a goat head (I apologize to the goats for any offense).
Today there are few forums where you can interestingly exchange opinions.
If it is a congenial virtual environment for you I am on Wilders, or MSFN but I write little in both.

I read that you are trying JShelter too.
I opened a problem with the help of Giorgio Maone in their forum:

[https://pagure.io/JShelter/webextension/issue/51](url)

/OT

Good day and sorry for the OT.

**Comment by Kees1958** [comment]
When you use a desktop a tip to drop fan speeds with ram air cooling.

Read your post on Wilders about PC temperatures. I run silence mode in my BIOS since I applied [this tweak (https://malwaretips.com/threads/kees1958-scrap-yard-desktop.110468/#post-964484)

Basically it is simple. The air temperature outside the PC casing is on average 10 to 15 degrees cooler (in Netherlands on average 10, in Italy it is probably 15 degrees Celcius in the summer). By adding a direct channel from outside the PC case to 5 to 7 cm above the CPU the air by which the CPU is cooled is colder. 

As you can side I used an old square plastic tupperware box which is wider at the top than at the bottom. By adding a 12 cm fan at the beginning of the air-tunnel/air-sleeve the air speed increases when the air leaves this plastic box just above the CPU and air temperature will drop a little more due to the venturi-effect.
