### ISSUE TITLE
9000 filters work great!

### ISSUE THREAD

**Issue by sillyjaybird** [Kees1958/W3C_annual_most_used_survey_blocklist#67]
Hello @Kees1958 I'm using your recommended lists with µBO hard mode (9000 total) and surfing is fast and no breakage. Thanks for keeping them updated!

**Comment by Kees1958** [comment]
Thanks, when you use hard mode, many filters make no sense anyway. You might have enabled it already otherwise setting 
https://github.com/gorhill/uBlock/wiki/Advanced-settings#filterauthormode  to true is an easy way to overrule blockrules from filters lists (brinhs back the old allow-noop-block option in uBo window)

**Comment by Kees1958** [comment]
thx
