### ISSUE TITLE
MV3-compatible EU list?

### ISSUE THREAD

**Issue by sillyjaybird** [Kees1958/W3C_annual_most_used_survey_blocklist#72]
I tried to subscribe to your list for the Adguard MV3 Experimental extension and it shows as incompatible, "must be in text format". Are you planning a converted list for MV3?

TIA
OS

**Comment by Kees1958** [comment]
Hi thanks for dropping the question

Actually I renamed the file to txt, so when I import it into AdGuardMv3 using the raw file it worked, but it exceeded the 5000 maximum, see image

![image](https://user-images.githubusercontent.com/30925856/191441322-3037e452-3a81-497a-8078-5ebf5c56f6b4.png)

I will slim down my most_used blocklist again, by excluding the tracking networks already blocked by Disconnect (which is used in Edge and Firefox), so you can use AG MV3 as complementary AdBlocker to Edge/Firerfox build in anti-tracking feature.

But because that is a lot of work when done manually, I have to write a script for it. At the moment I am very busy with other stuff, so I wil pick it up as soon as I got the time for it. For now it looks that I am very busy until Christmas holiday.

My mother of 89 needs a lot of care, and I am her only son. This makes a "mantelzorger". Mantelzorger is a strange Dutch title for a close relative who provides care for someone close who needs healthcare care, but does not get it because of government budget cuts in the Dutch healtcare system (with huge waiting list for elderly care as a result).

**Comment by sillyjaybird** [comment]
Hello Kees, 

I sympathize with your situation. We faced the same with my
mother-in-law who lived with us for 15 years. Whe she went on hospice,
we cared for her for 4 months or so at home until the situation simply
overwhelmed my wife, her sister and myself. Her sister eventually had to
go back home (2800 miles away), my wife had her job, and we were working
non-stop and burned out. 

There is no greater service you can offer than the care you provide.
Best wishes for her and you and your family.🙏🙏👍👍  

OS

On 2022-09-21 00:36, Kees1958 wrote:

> Hi thanks for dropping the question 
> 
> Actually I renamed the file to txt, so when I import it into AdGuardMv3 using the raw file it worked, but it exceeded the 5000 maximum, see image 
> 
> [1] 
> 
> I will slim down my most_used blocklist again, by excluding the tracking networks already blocked by Disconnect (which is used in Edge and Firefox), so you can use AG MV3 as complementary AdBlocker to Edge/Firerfox build in anti-tracking feature. 
> 
> But because that is a lot of work when done manually, I have to write a script for it. At the moment I am very busy with other stuff, so I wil pick it up as soon as I got the time for it. For now it looks that I am very busy until Christmas holiday. 
> 
> My mother of 89 needs a lot of care, and I am her only son. This makes a "mantelzorger". Mantelzorger is a strange Dutch title for a close relative who provides care for someone close who needs healthcare care, but does not get it because of government budget cuts in the Dutch healtcare system (with huge waiting list for elderly care as a result). 
> 
> --
> Reply to this email directly, view it on GitHub [2], or unsubscribe [3].
> You are receiving this because you authored the thread.Message ID: ***@***.***>
 

Links:
------
[1]
https://user-images.githubusercontent.com/30925856/191441322-3037e452-3a81-497a-8078-5ebf5c56f6b4.png
[2]
https://github.com/Kees1958/W3C_annual_most_used_survey_blocklist/issues/72#issuecomment-1253321600
[3]

**Comment by Kees1958** [comment]
I am running AdGuard Mv3 in Edge with https://raw.githubusercontent.com/Kees1958/W3C_annual_most_used_survey_blocklist/master/addendum_to_Edge_Firefox_build_in.txt

So I will  close this issue

**Comment by sillyjaybird** [comment]
Thanks @Kees1958

**Comment by sillyjaybird** [comment]
@Kees1958 have you found a way to use this list directly in Edge Tracking Prevention with no extension?

**Comment by Kees1958** [comment]
In the past there was a way, but Microsoft changed the location of Edge build-in to prevent this.

**Comment by Kees1958** [comment]
@sillyjaybird MV3 version: 
https://raw.githubusercontent.com/Kees1958/W3C_annual_most_used_survey_blocklist/master/EU_US_MV3_most_common_ad%2Btracking_networks.txt

Sorry I had forgotten you asked for it (hope you found it earlier)

**Comment by Kees1958** [comment]
https://raw.githubusercontent.com/Kees1958/W3C_annual_most_used_survey_blocklist/master/EU_US_MV3_most_common_ad%2Btracking_networks.txt
