### ISSUE TITLE
youtube_AG_rules list contains errors (8) when used in uBlock Origin

### ISSUE THREAD

**Issue by SampeiNihira** [Kees1958/W3C_annual_most_used_survey_blocklist#80]
Browser used Edge x64 latest build in W.10.
uBlock Origin v.1.57.2

I attach an image showing the 8 errors in the rules:
![3](https://github.com/Kees1958/W3C_annual_most_used_survey_blocklist/assets/44166263/7a65f7b5-683f-441b-9ef1-a77ab6181d83)

My best regards.

**Comment by Kees1958** [comment]
@SampeiNihira 

Thanks for reporting, but the AG is because it is for AdGuard. I don't use uBlock Origin anymore (unless Gorhill changes his minds and ads a user rule option to uBol, I think I stay on AG). AdGuard default filters contain these rules for Youtube. So AG users running the normal filterset, don't need this filterlist.
