### ISSUE TITLE
NOT AN ISSUE: explanation why I move away from AG rules!

### ISSUE THREAD

**Issue by sillyjaybird** [Kees1958/W3C_annual_most_used_survey_blocklist#87]
I see you're moving away from AG but it's not related to security or privacy concerns. I'm curious as to what your motivation is? What browser extension will you use when the change to MV3 rollout is complete? TIA.

**Comment by Kees1958** [comment]
AdGuard is good adblocking software, but my work laptop started disabling AdGuard because of group policies set by our company. Due to a large government contract acquired it is not allowed to install extensions anymore. In the adblocker category  I can only choose  out of Ghostery and AdblockPlus (which are devloped by German companieis). 

Because I like to keep my setup on my hone desktop the same as my work laptop, I decided to move to AdBlockPlus. I am using ABP on my work laptop since I made my the Personal_Blocklist_ABP (2 months ago). ABP is not as good as AG in blocking youtube ads, but performs similar or nearly as good on most other websites.

**Comment by sillyjaybird** [comment]
Thank you my friend!

**Comment by Kees1958** [comment]
Edit: I changed from AdBlockPlus to Ghostery, becaise Ghpstery now allows to add simple user rules and ghostery does better job than ABP (same clean websites as with AdGuard)

**Comment by Kees1958** [comment]
EDIT

Due to further safety restrictions on my work, I can't use my Desktop anymore for work, so I removed my Windows dual boot and only using Linux Mint 21.3 partition. On Linux I am using Ungoogled Chromium with uBlockOrigin lite. uBOL now offers AdGuard Dutch filter, which works well for me. Ungoogled runs in Flatpak with stripped rights and website permissions in Ungoogled to blocked/disabled except images (allowed), scripts (blocked except a few TLD's), sound, on device data (delete after session close). Only other extension is No-Eval (together with disabling V8 JIT, allowing javascript on few Top Level Domains and sandboxing should lower script based threats to minimum).

**Comment by Kees1958** [comment]
Because I met my targets early this year and I would officially retire end of this year, I am on paid leaf. I was allowed to keep my work laptop, but it came with a wiped SSD, so I am using Linux Mint Cinnamon now (never to old to learn something new :-)
